#ifndef WSCONFIGPORT_GLOBAL_H
#define WSCONFIGPORT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WSCONFIGPORT_LIBRARY)
#  define WSCONFIGPORTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WSCONFIGPORTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WSCONFIGPORT_GLOBAL_H
