#ifndef WSPLUGINSMANAGER_GLOBAL_H
#define WSPLUGINSMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WSPLUGINSMANAGER_LIBRARY)
#  define WSPLUGINSMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WSPLUGINSMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WSPLUGINSMANAGER_GLOBAL_H
