#ifndef WSMENUMANAGER_GLOBAL_H
#define WSMENUMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WSMENUMANAGER_LIBRARY)
#  define WSMENUMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WSMENUMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WSMENUMANAGER_GLOBAL_H
