#ifndef WSLOGWRITER_GLOBAL_H
#define WSLOGWRITER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WSLOGWRITER_LIBRARY)
#  define WSLOGWRITERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WSLOGWRITERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WSLOGWRITER_GLOBAL_H
