#ifndef WSPROJECTMANAGER_GLOBAL_H
#define WSPROJECTMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WSPROJECTMANAGER_LIBRARY)
#  define WSPROJECTMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WSPROJECTMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WSPROJECTMANAGER_GLOBAL_H
